### ISSUE TITLE
issue-1-user-can-search-recipes

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/entree-finder#1]
## ⚙️ Feature

The user can enter a keyword, or keywords, into a search form to find related recipes!

## 📐 Functionality

When the user opens the app, they will land on the home page. There will be a header with a Home Icon, which the user can use to navigate to the home page (Feature implemented later) and the Title of the app. Below this Header, the user will be able to interact with a search form to find relevant recipes!

#### Mobile:
![image](https://user-images.githubusercontent.com/76730244/172530136-7f7ceaee-c84d-4057-afbb-bfe5917d9430.png)

#### Desktop:
![image](https://user-images.githubusercontent.com/76730244/172530177-6d37af8d-5680-4c7f-911a-d0eabd8e1b3b.png)

## ✅ Task List

- [x] Create an HTML Skeleton
  - [x] Import font awesome
  - [x] Import css stylesheets
  - [x] Import Fonts (Playfair Display and Montserrat)
  - [x] Import script files (main and data) 
- [x] Create a header
  - [x] Add a Home Icon on the left
  - [x] Add the title to the app using Playfair Display
- [x] Add a section element to contain the search feature
- [x] **Inside of the section element
  - [x] Add text to instruct the user how to use the search feature
  - [x] Create a form
  - [x] Add a text input the user can use to enter keywords
  - [x] Add a submit button that will update window hash
- [x] **Inside of the main.js file**
  - [x] Add an event listener to the form element
  - [x] Assign null value to a variable which will later be updated to an array of object containing recipes
  - [x] When the user presses 'search' it will update the window hash with they keywords entered
  - [x] Impliment an XMLRequest function that will
    - [x]  Loop through the object
    - [x] Push specific data into an array of object
    - [x] Each recipe will be assigned to an index of the array as an object
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
