### ISSUE TITLE
Refactor: XHR Request and Application Functionality update

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/entree-finder#16]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Update Search Feature Functionality
  - [ ] update searchRecipes 
    - [x] update function comment 
    - [x] xhr.open parameters, remove 'false' for async argument
    - [x] remove vegan search restriction
    - [x] Hide api key!!
  - [x] update searchForm
    - [x] searchRecipes will update the window hash
    - [x] window hash update will render the search results
  - [x] update the applications name
    - [x] Food Journal?
    - [x] Would require CRUD (future features)
- [ ] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.

**Comment by OSAdams** [comment]
[Pull Request](https://github.com/OSAdams/ajax-project/pull/17)

**Comment by OSAdams** [comment]
[Pull Request](https://github.com/OSAdams/ajax-project/pull/17)
