### ISSUE TITLE
Bug: Data displaying incorrectly on recipe cards and pages

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/entree-finder#18]
#### Desired Behavior

When the user searches for a recipe, recipe cards will display data used with Free Meal API

#### Actual Behavior

When the user searches for a recipe, recipe cards are displaying incorrect information.

#### Steps to Reproduce

Search for a recipe using the search form.

## ✅ Task List

- [x] Console.log the data being returned in the XML Request
- [x] Update the renderRecipeCards function to
  - [x] Display labels and values accurate to the recipe
  - [x] Replace prep time with cuisine type
  - [x] Replace calories with the recipes source
  - [x] Replace element ID with 'idMeal'
- [x] Update the renderRecipe function to
  - [x] Update the Ingredient object
    - [x] Update to the strIngedient1 strMeasure1 to the ingredients list 
  - [x] Update the Instructions object
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
